name: Print out some useful information about the PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  setup:
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  when_open:
    name: When open
    needs: setup
    if: |
      github.event_name == 'pull_request' && (
      github.event.action == 'synchronize'
      || github.event.action == 'opened'
      || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        env:
          CURRENT_BRANCH: ${{needs.setup.outputs.branch}}
        run: |
          echo "Branch name: $CURRENT_BRANCH"
